# Generated by Django 3.2.9 on 2021-12-02 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_useradress_adress'),
    ]

    operations = [
        migrations.AddField(
            model_name='adress',
            name='cep',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adress',
            name='city',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adress',
            name='coordinates',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
